name: Deploy Lambda with Serverless

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: develop
    env:
      S3_BUCKET_NAME: ${{ vars.S3_BUCKET_NAME }}  
      LAMBDA_FUNCTION_NAME: ${{ vars.LAMBDA_FUNCTION_NAME }}  
      PACKAGE_PATH: ${{ vars.PACKAGE_PATH }} 
      S3_DEPLOY_PATH: ${{ vars.S3_DEPLOY_PATH }}
      NAME_BINARY: ${{ vars.NAME_BINARY }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      NODE_VERSION: ${{ vars.NODE_VERSION }} 
    

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 📌 Install dependencies
        run: npm install

      - name: serverless package
        uses: serverless/github-action@v3.2
        with:
          args: package
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}

      - name: 🔄 Upload package to S3
        run: |
          aws s3 cp ${{ env.PACKAGE_PATH }}/${{ env.NAME_BINARY }} s3://${{ env.S3_BUCKET_NAME }}/${{ env.S3_DEPLOY_PATH }}/${{ env.LAMBDA_FUNCTION_NAME }}.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: 🔄 Update Lambda with new source
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
            --s3-bucket ${{ env.S3_BUCKET_NAME }} \
            --s3-key ${{ env.S3_DEPLOY_PATH }}/${{ env.LAMBDA_FUNCTION_NAME }}.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
